name: vanguard
description: Vanguard is one of the leading Newspapers in Nigeria today . It has
  developed a rich heritage as the most entertaining, refreshing, authoritative,
  detailed and reader friendly newspaper in the country.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animations: ^2.0.3
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  expandable: ^5.0.1
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  google_nav_bar: ^5.0.6

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  onesignal_flutter: ^3.3.2
  path_provider: ^2.0.14
  progressive_image: ^2.0.0
  provider: ^6.0.3
  pull_to_refresh: ^2.0.0
  share_plus: ^4.0.10
  shimmer: ^2.0.0
  url_launcher: ^6.1.4

dev_dependencies:

  # hive database generators
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  google_mobile_ads:

flutter_icons:
  image_path_android: "assets/images/app_logo.png"
  image_path_ios: "assets/images/app_logo.png"
  remove_alpha_ios: true
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/animations/

  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
